version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
    groups:
      go-minor-patch:
        update-types:
          - minor
          - patch
      go-major:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: ci
      include: scope
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
      actions-major:
        update-types:
          - major

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
      include: scope
    groups:
      docker-minor-patch:
        update-types:
          - minor
          - patch
      docker-major:
        update-types:
          - major
