// Package version exposes the build-time version and git commit metadata
// embedded into the binary. The values come from commit.txt and version.txt,
// generated by `task generate` (which runs lookup_commit_hash.sh under the
// hood) and embedded via go:embed; both files are gitignored so a fresh
// clone must run `task generate` before `go build`.
package version
